name: C CI Workflow

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ] 

jobs:
  build-format-test:
    name: Build, Format Check & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make clang-format

      - name: Code formatting
        run: |
          echo "Formatting C code..."
          find . \( -name "*.c" -o -name "*.h" \) -exec clang-format -i -style=Google {} \;
          echo "Formatting completed."

      - name: Compile project
        run: |
          make
          echo "Build successful."

      - name: Basic executable check
        run: |
          if [ -f game ] && [ -x game ]; then
            echo "Executable 'game' exists and is executable."
          else
            echo "Error: Executable 'game' not found or not executable."
            exit 1
          fi